#!/bin/sh

# add more args here according to preference
ARGS="--volume=50"

notification(){
	notify-send "Now Playing:" "Lofi Radio ☕️🎶"
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Cat Trumpet"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification ;
            mpv "https://www.youtube.com/watch?v=5qap5aO4i9A" --no-video
			break
			;;
		2)
			notification ;
	    mpv "https://www.youtube.com/watch?v=EqQwYDf6DZM" --no-video
			break
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f mpv || main
